/*
 * Brevo API
 * Brevo provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/brevo  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  |   | 406  | Error. Not Acceptable  |   | 422  | Error. Unprocessable Entity | 
 *
 * OpenAPI spec version: 3.0.0
 * Contact: contact@brevo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package brevoModel;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SendSmtpEmailTo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2025-12-22T15:36:05.341+05:30")
public class SendSmtpEmailTo {
  @SerializedName("email")
  private String email = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("contactPixelTrackingConsent")
  private Boolean contactPixelTrackingConsent = null;

  public SendSmtpEmailTo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address of the recipient
   * @return email
  **/
  @ApiModelProperty(example = "jimmy98@example.com", required = true, value = "Email address of the recipient")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SendSmtpEmailTo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the recipient. Maximum allowed characters are 70.
   * @return name
  **/
  @ApiModelProperty(example = "Jimmy", value = "Name of the recipient. Maximum allowed characters are 70.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public SendSmtpEmailTo contactPixelTrackingConsent(Boolean contactPixelTrackingConsent) {
    this.contactPixelTrackingConsent = contactPixelTrackingConsent;
    return this;
  }

   /**
   * Consent of the recipient for open (pixel) tracking, resolved by the sender at send time. Considered only if the per-contact pixel tracking consent feature is enabled for your account. Pass `true` if this recipient has consented to open tracking, in which case the open pixel identifies the recipient. Pass `false` to anonymise the open event (counted in aggregate statistics only). If it is not passed, the recipient is treated as unknown consent status and the email is still sent (the open is anonymised unless your account tracks unknown-consent contacts). A value other than `true`/`false` is rejected. Ignored when the feature is not enabled for your account.
   * @return contactPixelTrackingConsent
  **/
  @ApiModelProperty(example = "true", value = "Consent of the recipient for open (pixel) tracking, resolved by the sender at send time. Considered only if the per-contact pixel tracking consent feature is enabled for your account. Pass `true` if this recipient has consented to open tracking, in which case the open pixel identifies the recipient. Pass `false` to anonymise the open event (counted in aggregate statistics only). If it is not passed, the recipient is treated as unknown consent status and the email is still sent (the open is anonymised unless your account tracks unknown-consent contacts). A value other than `true`/`false` is rejected. Ignored when the feature is not enabled for your account.")
  public Boolean isContactPixelTrackingConsent() {
    return contactPixelTrackingConsent;
  }

  public void setContactPixelTrackingConsent(Boolean contactPixelTrackingConsent) {
    this.contactPixelTrackingConsent = contactPixelTrackingConsent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    SendSmtpEmailTo sendSmtpEmailTo = (SendSmtpEmailTo) o;
    return ObjectUtils.equals(this.email, sendSmtpEmailTo.email) &&
    ObjectUtils.equals(this.name, sendSmtpEmailTo.name) &&
    ObjectUtils.equals(this.contactPixelTrackingConsent, sendSmtpEmailTo.contactPixelTrackingConsent);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(email, name, contactPixelTrackingConsent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendSmtpEmailTo {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contactPixelTrackingConsent: ").append(toIndentedString(contactPixelTrackingConsent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

